### ISSUE TITLE
Build failure; package needs updating with latest from djs55

### ISSUE THREAD

**Issue by mcclurmc** [xapi-project/message-switch#1]
```opam install message_switch``` gives:

```
# + ocamlfind ocamlc -c -g -I core -package unix -package threads -package rpclib.syntax -package rpclib.json -package rpclib -package re.str -package re -package oclock -package lw
t.unix -package lwt.syntax -package lwt -package cohttp.lwt -package cohttp -syntax camlp4o -thread -I core -o core/protocol_lwt.cmo core/protocol_lwt.ml
# File "core/protocol_lwt.ml", line 79, characters 40-42:
# Error: Signature mismatch:
#        ...
#        The field `flush' is required but not provided
```

This can be fixed by pinning message_switch to the latest from djs55.

I'd update xapi-project's message_switch repo myself, but I don't know if anything we've got is specifically depending on this particular version, so I'm assigning this to @djs55.

Merry Christmas! :)

**Comment by djs55** [comment]
... and Merry Christmas to you! Umm, I think this has been fixed now...
